language: 
  - node_js
  - istanbul
node_js:
  - "node"
  - "iojs"
istanbul:
 - "latest"
script: npm test
before_script:
  - npm -d install

after_script:
- cat ./build/coverage/**/lcov.info | .node_modules/coveralls/bin/coveralls.js