language: 
  - node_js
  - istanbul
node_js:
  - "node"
  - "iojs"
istanbul:
 - "latest"
script: npm test
before_script:
  - npm install

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN